version: '3'
services:
  bridge:
    build:
      dockerfile: "ops/bridge/Dockerfile"
      context: .
    command: bash -c "/bridge/bridge --migrate-db && /bridge/bridge"
    ports:
      - "8001:8001"
    depends_on:
      - pg
    volumes:
      - ./spec/fixtures/bridge:/app
  pg:
    image: postgres:9.6
    ports:
      - "5432:5432"
    volumes:
      - pg:/var/lib/postgresql/data
  stellar_app:
    build: spec/stellar_app
    command: bash -c "bundle exec rails s -p 3000 -b 0.0.0.0"
    ports:
      - "3000:3000"
    volumes:
      - ./spec/stellar_app:/app
      - bundle:/bundle
    depends_on:
      - pg
  bundle:
    image: busybox
    volumes:
      - /bundle
volumes:
  pg:
  bridge:
  bundle:
