version: '2'
services:
  bridge:
    build:
      dockerfile: "ops/bridge/Dockerfile"
      context: .
    command: bash -c "/bridge/bridge --migrate-db && /bridge/bridge"
    ports:
      - "8001:8001"
    depends_on:
      - bridge_db
    volumes:
      - ./spec/fixtures/bridge:/app
  bridge_db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    volumes:
      - bridge_db:/var/lib/postgresql/data
volumes:
  bridge_db:
  bridge:
